-- synthesis library addressgen

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

PACKAGE utils IS
  TYPE CORE_STATE_T IS (READY, CALCULATING);

  SUBTYPE BYTE_T IS STD_LOGIC_VECTOR(7 DOWNTO 0);

  TYPE CALCULATED_SHA_T IS ARRAY (31 DOWNTO 0) OF BYTE_T;
  TYPE GENERATED_ECDSA_T IS ARRAY (32 DOWNTO 0) OF BYTE_T;
END PACKAGE;
